AWSTemplateFormatVersion: '2010-09-09'
Description: 'Complete AWS Stack for No-Code AI Chatbot Builder'

Parameters:
  ProjectName:
    Type: String
    Default: chatbot-builder
    Description: Project name for resource naming
  
  GoogleApiKey:
    Type: String
    NoEcho: true
    Description: Google Gemini API Key
  
  FrontendDomain:
    Type: String
    Default: ''
    Description: Custom domain for frontend (optional)

Resources:
  # ==================== Cognito User Pool ====================
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${ProjectName}-users'
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: false
        - Name: name
          Required: false
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      UserPoolTags:
        Project: !Ref ProjectName

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${ProjectName}-web-client'
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30

  # ==================== DynamoDB Tables ====================
  VectorEmbeddingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-vectors'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: bot_id
          AttributeType: S
        - AttributeName: chunk_id
          AttributeType: S
        - AttributeName: filename
          AttributeType: S
      KeySchema:
        - AttributeName: bot_id
          KeyType: HASH
        - AttributeName: chunk_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: filename-index
          KeySchema:
            - AttributeName: bot_id
              KeyType: HASH
            - AttributeName: filename
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  BotCollectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-bots'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: bot_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: bot_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # ==================== S3 Bucket ====================
  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-documents-${AWS::AccountId}'
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
            AllowedHeaders:
              - '*'
            MaxAge: 3000
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # ==================== IAM Roles ====================
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchWriteItem
                  - dynamodb:BatchGetItem
                Resource:
                  - !GetAtt VectorEmbeddingsTable.Arn
                  - !GetAtt BotCollectionsTable.Arn
                  - !Sub '${VectorEmbeddingsTable.Arn}/index/*'
                  - !Sub '${BotCollectionsTable.Arn}/index/*'
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt DocumentsBucket.Arn
                  - !Sub '${DocumentsBucket.Arn}/*'
        - PolicyName: CognitoAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:AdminGetUser
                  - cognito-idp:AdminCreateUser
                  - cognito-idp:AdminDeleteUser
                  - cognito-idp:ListUsers
                Resource:
                  - !GetAtt UserPool.Arn

  # ==================== Lambda Functions ====================
  AuthFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-auth'
      Runtime: python3.11
      Handler: auth_handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Auth function placeholder'}
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region
          COGNITO_USER_POOL_ID: !Ref UserPool
          COGNITO_APP_CLIENT_ID: !Ref UserPoolClient
      Timeout: 30
      MemorySize: 256

  UploadFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-upload'
      Runtime: python3.11
      Handler: upload_handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Upload function placeholder'}
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region
          S3_BUCKET_NAME: !Ref DocumentsBucket
          DYNAMODB_VECTORS_TABLE: !Ref VectorEmbeddingsTable
          DYNAMODB_BOTS_TABLE: !Ref BotCollectionsTable
          GOOGLE_API_KEY: !Ref GoogleApiKey
      Timeout: 300
      MemorySize: 1024

  ChatFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-chat'
      Runtime: python3.11
      Handler: chat_handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Chat function placeholder'}
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region
          DYNAMODB_VECTORS_TABLE: !Ref VectorEmbeddingsTable
          GOOGLE_API_KEY: !Ref GoogleApiKey
      Timeout: 60
      MemorySize: 512

  BotsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-bots'
      Runtime: python3.11
      Handler: bots_handler.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {'statusCode': 200, 'body': 'Bots function placeholder'}
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region
          S3_BUCKET_NAME: !Ref DocumentsBucket
          DYNAMODB_VECTORS_TABLE: !Ref VectorEmbeddingsTable
          DYNAMODB_BOTS_TABLE: !Ref BotCollectionsTable
      Timeout: 60
      MemorySize: 512

  # ==================== API Gateway ====================
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${ProjectName}-api'
      Description: API for Chatbot Builder
      EndpointConfiguration:
        Types:
          - REGIONAL

  # Cognito Authorizer
  CognitoAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CognitoAuthorizer
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId: !Ref RestApi
      ProviderARNs:
        - !GetAtt UserPool.Arn

  # API Resources and Methods would go here
  # (Simplified for brevity - see full implementation in separate file)

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - AuthFunction
      - UploadFunction
      - ChatFunction
      - BotsFunction
    Properties:
      RestApiId: !Ref RestApi
      StageName: prod

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub '${ProjectName}-UserPoolId'

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${ProjectName}-UserPoolClientId'

  ApiGatewayUrl:
    Description: API Gateway URL
    Value: !Sub 'https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export:
      Name: !Sub '${ProjectName}-ApiUrl'

  DocumentsBucketName:
    Description: S3 Bucket for Documents
    Value: !Ref DocumentsBucket
    Export:
      Name: !Sub '${ProjectName}-DocumentsBucket'

  VectorTableName:
    Description: DynamoDB Vectors Table
    Value: !Ref VectorEmbeddingsTable
    Export:
      Name: !Sub '${ProjectName}-VectorsTable'

  BotsTableName:
    Description: DynamoDB Bots Table
    Value: !Ref BotCollectionsTable
    Export:
      Name: !Sub '${ProjectName}-BotsTable'
